/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectSlugIndexRouteImport } from './routes/$projectSlug/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsImportRouteImport } from './routes/projects/import'
import { Route as ProjectSlugRunsRouteImport } from './routes/$projectSlug/runs'
import { Route as ProjectSlugApiKeysRouteImport } from './routes/$projectSlug/api-keys'
import { Route as ProjectSlugHostsIndexRouteImport } from './routes/$projectSlug/hosts/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectSlugSetupSettingsRouteImport } from './routes/$projectSlug/setup/settings'
import { Route as ProjectSlugSetupFleetRouteImport } from './routes/$projectSlug/setup/fleet'
import { Route as ProjectSlugSetupDoctorRouteImport } from './routes/$projectSlug/setup/doctor'
import { Route as ProjectSlugRunsRunIdRouteImport } from './routes/$projectSlug/runs/$runId'
import { Route as ProjectSlugAdvancedEditorRouteImport } from './routes/$projectSlug/advanced/editor'
import { Route as ProjectSlugAdvancedCommandsRouteImport } from './routes/$projectSlug/advanced/commands'
import { Route as ProjectSlugHostsHostIndexRouteImport } from './routes/$projectSlug/hosts/$host/index'
import { Route as ProjectSlugHostsHostSettingsRouteImport } from './routes/$projectSlug/hosts/$host/settings'
import { Route as ProjectSlugHostsHostSecretsRouteImport } from './routes/$projectSlug/hosts/$host/secrets'
import { Route as ProjectSlugHostsHostRestartRouteImport } from './routes/$projectSlug/hosts/$host/restart'
import { Route as ProjectSlugHostsHostLogsRouteImport } from './routes/$projectSlug/hosts/$host/logs'
import { Route as ProjectSlugHostsHostDeployRouteImport } from './routes/$projectSlug/hosts/$host/deploy'
import { Route as ProjectSlugHostsHostBootstrapRouteImport } from './routes/$projectSlug/hosts/$host/bootstrap'
import { Route as ProjectSlugHostsHostAuditRouteImport } from './routes/$projectSlug/hosts/$host/audit'
import { Route as ProjectSlugHostsHostAgentsRouteImport } from './routes/$projectSlug/hosts/$host/agents'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugIndexRoute = ProjectSlugIndexRouteImport.update({
  id: '/$projectSlug/',
  path: '/$projectSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsImportRoute = ProjectsImportRouteImport.update({
  id: '/projects/import',
  path: '/projects/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRunsRoute = ProjectSlugRunsRouteImport.update({
  id: '/$projectSlug/runs',
  path: '/$projectSlug/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugApiKeysRoute = ProjectSlugApiKeysRouteImport.update({
  id: '/$projectSlug/api-keys',
  path: '/$projectSlug/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugHostsIndexRoute = ProjectSlugHostsIndexRouteImport.update({
  id: '/$projectSlug/hosts/',
  path: '/$projectSlug/hosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugSetupSettingsRoute =
  ProjectSlugSetupSettingsRouteImport.update({
    id: '/$projectSlug/setup/settings',
    path: '/$projectSlug/setup/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugSetupFleetRoute = ProjectSlugSetupFleetRouteImport.update({
  id: '/$projectSlug/setup/fleet',
  path: '/$projectSlug/setup/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugSetupDoctorRoute = ProjectSlugSetupDoctorRouteImport.update({
  id: '/$projectSlug/setup/doctor',
  path: '/$projectSlug/setup/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRunsRunIdRoute = ProjectSlugRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ProjectSlugRunsRoute,
} as any)
const ProjectSlugAdvancedEditorRoute =
  ProjectSlugAdvancedEditorRouteImport.update({
    id: '/$projectSlug/advanced/editor',
    path: '/$projectSlug/advanced/editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugAdvancedCommandsRoute =
  ProjectSlugAdvancedCommandsRouteImport.update({
    id: '/$projectSlug/advanced/commands',
    path: '/$projectSlug/advanced/commands',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugHostsHostIndexRoute =
  ProjectSlugHostsHostIndexRouteImport.update({
    id: '/$projectSlug/hosts/$host/',
    path: '/$projectSlug/hosts/$host/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugHostsHostSettingsRoute =
  ProjectSlugHostsHostSettingsRouteImport.update({
    id: '/$projectSlug/hosts/$host/settings',
    path: '/$projectSlug/hosts/$host/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugHostsHostSecretsRoute =
  ProjectSlugHostsHostSecretsRouteImport.update({
    id: '/$projectSlug/hosts/$host/secrets',
    path: '/$projectSlug/hosts/$host/secrets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugHostsHostRestartRoute =
  ProjectSlugHostsHostRestartRouteImport.update({
    id: '/$projectSlug/hosts/$host/restart',
    path: '/$projectSlug/hosts/$host/restart',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugHostsHostLogsRoute =
  ProjectSlugHostsHostLogsRouteImport.update({
    id: '/$projectSlug/hosts/$host/logs',
    path: '/$projectSlug/hosts/$host/logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugHostsHostDeployRoute =
  ProjectSlugHostsHostDeployRouteImport.update({
    id: '/$projectSlug/hosts/$host/deploy',
    path: '/$projectSlug/hosts/$host/deploy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugHostsHostBootstrapRoute =
  ProjectSlugHostsHostBootstrapRouteImport.update({
    id: '/$projectSlug/hosts/$host/bootstrap',
    path: '/$projectSlug/hosts/$host/bootstrap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugHostsHostAuditRoute =
  ProjectSlugHostsHostAuditRouteImport.update({
    id: '/$projectSlug/hosts/$host/audit',
    path: '/$projectSlug/hosts/$host/audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectSlugHostsHostAgentsRoute =
  ProjectSlugHostsHostAgentsRouteImport.update({
    id: '/$projectSlug/hosts/$host/agents',
    path: '/$projectSlug/hosts/$host/agents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/$projectSlug/api-keys': typeof ProjectSlugApiKeysRoute
  '/$projectSlug/runs': typeof ProjectSlugRunsRouteWithChildren
  '/projects/import': typeof ProjectsImportRoute
  '/projects/new': typeof ProjectsNewRoute
  '/$projectSlug/': typeof ProjectSlugIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/$projectSlug/advanced/commands': typeof ProjectSlugAdvancedCommandsRoute
  '/$projectSlug/advanced/editor': typeof ProjectSlugAdvancedEditorRoute
  '/$projectSlug/runs/$runId': typeof ProjectSlugRunsRunIdRoute
  '/$projectSlug/setup/doctor': typeof ProjectSlugSetupDoctorRoute
  '/$projectSlug/setup/fleet': typeof ProjectSlugSetupFleetRoute
  '/$projectSlug/setup/settings': typeof ProjectSlugSetupSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$projectSlug/hosts/': typeof ProjectSlugHostsIndexRoute
  '/$projectSlug/hosts/$host/agents': typeof ProjectSlugHostsHostAgentsRoute
  '/$projectSlug/hosts/$host/audit': typeof ProjectSlugHostsHostAuditRoute
  '/$projectSlug/hosts/$host/bootstrap': typeof ProjectSlugHostsHostBootstrapRoute
  '/$projectSlug/hosts/$host/deploy': typeof ProjectSlugHostsHostDeployRoute
  '/$projectSlug/hosts/$host/logs': typeof ProjectSlugHostsHostLogsRoute
  '/$projectSlug/hosts/$host/restart': typeof ProjectSlugHostsHostRestartRoute
  '/$projectSlug/hosts/$host/secrets': typeof ProjectSlugHostsHostSecretsRoute
  '/$projectSlug/hosts/$host/settings': typeof ProjectSlugHostsHostSettingsRoute
  '/$projectSlug/hosts/$host/': typeof ProjectSlugHostsHostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/$projectSlug/api-keys': typeof ProjectSlugApiKeysRoute
  '/$projectSlug/runs': typeof ProjectSlugRunsRouteWithChildren
  '/projects/import': typeof ProjectsImportRoute
  '/projects/new': typeof ProjectsNewRoute
  '/$projectSlug': typeof ProjectSlugIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/$projectSlug/advanced/commands': typeof ProjectSlugAdvancedCommandsRoute
  '/$projectSlug/advanced/editor': typeof ProjectSlugAdvancedEditorRoute
  '/$projectSlug/runs/$runId': typeof ProjectSlugRunsRunIdRoute
  '/$projectSlug/setup/doctor': typeof ProjectSlugSetupDoctorRoute
  '/$projectSlug/setup/fleet': typeof ProjectSlugSetupFleetRoute
  '/$projectSlug/setup/settings': typeof ProjectSlugSetupSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$projectSlug/hosts': typeof ProjectSlugHostsIndexRoute
  '/$projectSlug/hosts/$host/agents': typeof ProjectSlugHostsHostAgentsRoute
  '/$projectSlug/hosts/$host/audit': typeof ProjectSlugHostsHostAuditRoute
  '/$projectSlug/hosts/$host/bootstrap': typeof ProjectSlugHostsHostBootstrapRoute
  '/$projectSlug/hosts/$host/deploy': typeof ProjectSlugHostsHostDeployRoute
  '/$projectSlug/hosts/$host/logs': typeof ProjectSlugHostsHostLogsRoute
  '/$projectSlug/hosts/$host/restart': typeof ProjectSlugHostsHostRestartRoute
  '/$projectSlug/hosts/$host/secrets': typeof ProjectSlugHostsHostSecretsRoute
  '/$projectSlug/hosts/$host/settings': typeof ProjectSlugHostsHostSettingsRoute
  '/$projectSlug/hosts/$host': typeof ProjectSlugHostsHostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/$projectSlug/api-keys': typeof ProjectSlugApiKeysRoute
  '/$projectSlug/runs': typeof ProjectSlugRunsRouteWithChildren
  '/projects/import': typeof ProjectsImportRoute
  '/projects/new': typeof ProjectsNewRoute
  '/$projectSlug/': typeof ProjectSlugIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/$projectSlug/advanced/commands': typeof ProjectSlugAdvancedCommandsRoute
  '/$projectSlug/advanced/editor': typeof ProjectSlugAdvancedEditorRoute
  '/$projectSlug/runs/$runId': typeof ProjectSlugRunsRunIdRoute
  '/$projectSlug/setup/doctor': typeof ProjectSlugSetupDoctorRoute
  '/$projectSlug/setup/fleet': typeof ProjectSlugSetupFleetRoute
  '/$projectSlug/setup/settings': typeof ProjectSlugSetupSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$projectSlug/hosts/': typeof ProjectSlugHostsIndexRoute
  '/$projectSlug/hosts/$host/agents': typeof ProjectSlugHostsHostAgentsRoute
  '/$projectSlug/hosts/$host/audit': typeof ProjectSlugHostsHostAuditRoute
  '/$projectSlug/hosts/$host/bootstrap': typeof ProjectSlugHostsHostBootstrapRoute
  '/$projectSlug/hosts/$host/deploy': typeof ProjectSlugHostsHostDeployRoute
  '/$projectSlug/hosts/$host/logs': typeof ProjectSlugHostsHostLogsRoute
  '/$projectSlug/hosts/$host/restart': typeof ProjectSlugHostsHostRestartRoute
  '/$projectSlug/hosts/$host/secrets': typeof ProjectSlugHostsHostSecretsRoute
  '/$projectSlug/hosts/$host/settings': typeof ProjectSlugHostsHostSettingsRoute
  '/$projectSlug/hosts/$host/': typeof ProjectSlugHostsHostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/$projectSlug/api-keys'
    | '/$projectSlug/runs'
    | '/projects/import'
    | '/projects/new'
    | '/$projectSlug/'
    | '/projects/'
    | '/$projectSlug/advanced/commands'
    | '/$projectSlug/advanced/editor'
    | '/$projectSlug/runs/$runId'
    | '/$projectSlug/setup/doctor'
    | '/$projectSlug/setup/fleet'
    | '/$projectSlug/setup/settings'
    | '/api/auth/$'
    | '/$projectSlug/hosts/'
    | '/$projectSlug/hosts/$host/agents'
    | '/$projectSlug/hosts/$host/audit'
    | '/$projectSlug/hosts/$host/bootstrap'
    | '/$projectSlug/hosts/$host/deploy'
    | '/$projectSlug/hosts/$host/logs'
    | '/$projectSlug/hosts/$host/restart'
    | '/$projectSlug/hosts/$host/secrets'
    | '/$projectSlug/hosts/$host/settings'
    | '/$projectSlug/hosts/$host/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/$projectSlug/api-keys'
    | '/$projectSlug/runs'
    | '/projects/import'
    | '/projects/new'
    | '/$projectSlug'
    | '/projects'
    | '/$projectSlug/advanced/commands'
    | '/$projectSlug/advanced/editor'
    | '/$projectSlug/runs/$runId'
    | '/$projectSlug/setup/doctor'
    | '/$projectSlug/setup/fleet'
    | '/$projectSlug/setup/settings'
    | '/api/auth/$'
    | '/$projectSlug/hosts'
    | '/$projectSlug/hosts/$host/agents'
    | '/$projectSlug/hosts/$host/audit'
    | '/$projectSlug/hosts/$host/bootstrap'
    | '/$projectSlug/hosts/$host/deploy'
    | '/$projectSlug/hosts/$host/logs'
    | '/$projectSlug/hosts/$host/restart'
    | '/$projectSlug/hosts/$host/secrets'
    | '/$projectSlug/hosts/$host/settings'
    | '/$projectSlug/hosts/$host'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/$projectSlug/api-keys'
    | '/$projectSlug/runs'
    | '/projects/import'
    | '/projects/new'
    | '/$projectSlug/'
    | '/projects/'
    | '/$projectSlug/advanced/commands'
    | '/$projectSlug/advanced/editor'
    | '/$projectSlug/runs/$runId'
    | '/$projectSlug/setup/doctor'
    | '/$projectSlug/setup/fleet'
    | '/$projectSlug/setup/settings'
    | '/api/auth/$'
    | '/$projectSlug/hosts/'
    | '/$projectSlug/hosts/$host/agents'
    | '/$projectSlug/hosts/$host/audit'
    | '/$projectSlug/hosts/$host/bootstrap'
    | '/$projectSlug/hosts/$host/deploy'
    | '/$projectSlug/hosts/$host/logs'
    | '/$projectSlug/hosts/$host/restart'
    | '/$projectSlug/hosts/$host/secrets'
    | '/$projectSlug/hosts/$host/settings'
    | '/$projectSlug/hosts/$host/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  ProjectSlugApiKeysRoute: typeof ProjectSlugApiKeysRoute
  ProjectSlugRunsRoute: typeof ProjectSlugRunsRouteWithChildren
  ProjectsImportRoute: typeof ProjectsImportRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectSlugIndexRoute: typeof ProjectSlugIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectSlugAdvancedCommandsRoute: typeof ProjectSlugAdvancedCommandsRoute
  ProjectSlugAdvancedEditorRoute: typeof ProjectSlugAdvancedEditorRoute
  ProjectSlugSetupDoctorRoute: typeof ProjectSlugSetupDoctorRoute
  ProjectSlugSetupFleetRoute: typeof ProjectSlugSetupFleetRoute
  ProjectSlugSetupSettingsRoute: typeof ProjectSlugSetupSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ProjectSlugHostsIndexRoute: typeof ProjectSlugHostsIndexRoute
  ProjectSlugHostsHostAgentsRoute: typeof ProjectSlugHostsHostAgentsRoute
  ProjectSlugHostsHostAuditRoute: typeof ProjectSlugHostsHostAuditRoute
  ProjectSlugHostsHostBootstrapRoute: typeof ProjectSlugHostsHostBootstrapRoute
  ProjectSlugHostsHostDeployRoute: typeof ProjectSlugHostsHostDeployRoute
  ProjectSlugHostsHostLogsRoute: typeof ProjectSlugHostsHostLogsRoute
  ProjectSlugHostsHostRestartRoute: typeof ProjectSlugHostsHostRestartRoute
  ProjectSlugHostsHostSecretsRoute: typeof ProjectSlugHostsHostSecretsRoute
  ProjectSlugHostsHostSettingsRoute: typeof ProjectSlugHostsHostSettingsRoute
  ProjectSlugHostsHostIndexRoute: typeof ProjectSlugHostsHostIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/': {
      id: '/$projectSlug/'
      path: '/$projectSlug'
      fullPath: '/$projectSlug/'
      preLoaderRoute: typeof ProjectSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/import': {
      id: '/projects/import'
      path: '/projects/import'
      fullPath: '/projects/import'
      preLoaderRoute: typeof ProjectsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/runs': {
      id: '/$projectSlug/runs'
      path: '/$projectSlug/runs'
      fullPath: '/$projectSlug/runs'
      preLoaderRoute: typeof ProjectSlugRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/api-keys': {
      id: '/$projectSlug/api-keys'
      path: '/$projectSlug/api-keys'
      fullPath: '/$projectSlug/api-keys'
      preLoaderRoute: typeof ProjectSlugApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/': {
      id: '/$projectSlug/hosts/'
      path: '/$projectSlug/hosts'
      fullPath: '/$projectSlug/hosts/'
      preLoaderRoute: typeof ProjectSlugHostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/setup/settings': {
      id: '/$projectSlug/setup/settings'
      path: '/$projectSlug/setup/settings'
      fullPath: '/$projectSlug/setup/settings'
      preLoaderRoute: typeof ProjectSlugSetupSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/setup/fleet': {
      id: '/$projectSlug/setup/fleet'
      path: '/$projectSlug/setup/fleet'
      fullPath: '/$projectSlug/setup/fleet'
      preLoaderRoute: typeof ProjectSlugSetupFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/setup/doctor': {
      id: '/$projectSlug/setup/doctor'
      path: '/$projectSlug/setup/doctor'
      fullPath: '/$projectSlug/setup/doctor'
      preLoaderRoute: typeof ProjectSlugSetupDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/runs/$runId': {
      id: '/$projectSlug/runs/$runId'
      path: '/$runId'
      fullPath: '/$projectSlug/runs/$runId'
      preLoaderRoute: typeof ProjectSlugRunsRunIdRouteImport
      parentRoute: typeof ProjectSlugRunsRoute
    }
    '/$projectSlug/advanced/editor': {
      id: '/$projectSlug/advanced/editor'
      path: '/$projectSlug/advanced/editor'
      fullPath: '/$projectSlug/advanced/editor'
      preLoaderRoute: typeof ProjectSlugAdvancedEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/advanced/commands': {
      id: '/$projectSlug/advanced/commands'
      path: '/$projectSlug/advanced/commands'
      fullPath: '/$projectSlug/advanced/commands'
      preLoaderRoute: typeof ProjectSlugAdvancedCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/$host/': {
      id: '/$projectSlug/hosts/$host/'
      path: '/$projectSlug/hosts/$host'
      fullPath: '/$projectSlug/hosts/$host/'
      preLoaderRoute: typeof ProjectSlugHostsHostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/$host/settings': {
      id: '/$projectSlug/hosts/$host/settings'
      path: '/$projectSlug/hosts/$host/settings'
      fullPath: '/$projectSlug/hosts/$host/settings'
      preLoaderRoute: typeof ProjectSlugHostsHostSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/$host/secrets': {
      id: '/$projectSlug/hosts/$host/secrets'
      path: '/$projectSlug/hosts/$host/secrets'
      fullPath: '/$projectSlug/hosts/$host/secrets'
      preLoaderRoute: typeof ProjectSlugHostsHostSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/$host/restart': {
      id: '/$projectSlug/hosts/$host/restart'
      path: '/$projectSlug/hosts/$host/restart'
      fullPath: '/$projectSlug/hosts/$host/restart'
      preLoaderRoute: typeof ProjectSlugHostsHostRestartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/$host/logs': {
      id: '/$projectSlug/hosts/$host/logs'
      path: '/$projectSlug/hosts/$host/logs'
      fullPath: '/$projectSlug/hosts/$host/logs'
      preLoaderRoute: typeof ProjectSlugHostsHostLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/$host/deploy': {
      id: '/$projectSlug/hosts/$host/deploy'
      path: '/$projectSlug/hosts/$host/deploy'
      fullPath: '/$projectSlug/hosts/$host/deploy'
      preLoaderRoute: typeof ProjectSlugHostsHostDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/$host/bootstrap': {
      id: '/$projectSlug/hosts/$host/bootstrap'
      path: '/$projectSlug/hosts/$host/bootstrap'
      fullPath: '/$projectSlug/hosts/$host/bootstrap'
      preLoaderRoute: typeof ProjectSlugHostsHostBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/$host/audit': {
      id: '/$projectSlug/hosts/$host/audit'
      path: '/$projectSlug/hosts/$host/audit'
      fullPath: '/$projectSlug/hosts/$host/audit'
      preLoaderRoute: typeof ProjectSlugHostsHostAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/hosts/$host/agents': {
      id: '/$projectSlug/hosts/$host/agents'
      path: '/$projectSlug/hosts/$host/agents'
      fullPath: '/$projectSlug/hosts/$host/agents'
      preLoaderRoute: typeof ProjectSlugHostsHostAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectSlugRunsRouteChildren {
  ProjectSlugRunsRunIdRoute: typeof ProjectSlugRunsRunIdRoute
}

const ProjectSlugRunsRouteChildren: ProjectSlugRunsRouteChildren = {
  ProjectSlugRunsRunIdRoute: ProjectSlugRunsRunIdRoute,
}

const ProjectSlugRunsRouteWithChildren = ProjectSlugRunsRoute._addFileChildren(
  ProjectSlugRunsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  ProjectSlugApiKeysRoute: ProjectSlugApiKeysRoute,
  ProjectSlugRunsRoute: ProjectSlugRunsRouteWithChildren,
  ProjectsImportRoute: ProjectsImportRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectSlugIndexRoute: ProjectSlugIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectSlugAdvancedCommandsRoute: ProjectSlugAdvancedCommandsRoute,
  ProjectSlugAdvancedEditorRoute: ProjectSlugAdvancedEditorRoute,
  ProjectSlugSetupDoctorRoute: ProjectSlugSetupDoctorRoute,
  ProjectSlugSetupFleetRoute: ProjectSlugSetupFleetRoute,
  ProjectSlugSetupSettingsRoute: ProjectSlugSetupSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ProjectSlugHostsIndexRoute: ProjectSlugHostsIndexRoute,
  ProjectSlugHostsHostAgentsRoute: ProjectSlugHostsHostAgentsRoute,
  ProjectSlugHostsHostAuditRoute: ProjectSlugHostsHostAuditRoute,
  ProjectSlugHostsHostBootstrapRoute: ProjectSlugHostsHostBootstrapRoute,
  ProjectSlugHostsHostDeployRoute: ProjectSlugHostsHostDeployRoute,
  ProjectSlugHostsHostLogsRoute: ProjectSlugHostsHostLogsRoute,
  ProjectSlugHostsHostRestartRoute: ProjectSlugHostsHostRestartRoute,
  ProjectSlugHostsHostSecretsRoute: ProjectSlugHostsHostSecretsRoute,
  ProjectSlugHostsHostSettingsRoute: ProjectSlugHostsHostSettingsRoute,
  ProjectSlugHostsHostIndexRoute: ProjectSlugHostsHostIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
