export const setupFieldHelp = {
  hosts: {
    defaultHost: "Default host used by doctor/bootstrap/deploy when you leave host unset.",
    editHost: "Select which host config you’re editing under `hosts.<host>`.",
    addHost: "Adds a new host entry under `hosts.<host>` (config only; no infra created yet).",
    enabled: "Toggles whether this host is managed/deployed by clawdlets.",
    diskDevice: "Block device to install NixOS onto (usually `/dev/sda` on Hetzner). Must start with `/dev/`.",
    targetHost: "SSH destination used for deploy/ops after bootstrap (ssh alias or `user@host`).",
    adminCidr: "CIDR allowed to reach admin SSH during bootstrap (recommend your current IP `/32`). Use Detect to autofill from your public IP.",
    sshPubkeyFile: "Local `.pub` file to authorize on the host during provisioning.",
    sshExposure: "How SSH is exposed: `bootstrap` (temporary), `tailnet` (recommended), or `public` (risky).",
    tailnet: "Tailnet integration mode. `tailscale` enables Tailscale-based access; `none` disables it.",
    hetznerServerType: "Hetzner server type (e.g. `cx43`). Used by provisioning.",
    hetznerLocation: "Hetzner DC location (e.g. `nbg1`).",
    hetznerImage: "Optional Hetzner image override (usually leave empty when using nixos-anywhere).",
    flakeHost: "Override the Nix flake host target (advanced; usually leave empty).",
    agentModelPrimary: "Default model identifier used by agents on this host (provider/model).",
    sshKeyPaste: "Paste one or more public keys to append to `sshAuthorizedKeys` for this host.",
    sshKeyFile: "Read a local `.pub` file and append it to `sshAuthorizedKeys`.",
    knownHostsFile: "Optionally import entries from your local `known_hosts` for safer SSH pinning.",
  },
  fleet: {
    guildId: "Discord guild/server ID used by fleet integrations.",
    codexEnable: "Enables Codex integration in the fleet config.",
    resticEnable: "Enables restic backups configuration in the fleet config.",
    resticRepo: "Restic repository URL/path used for backups (only when restic is enabled).",
    jsonEditor: "Edit the full `fleet/clawdlets.json` as JSON (validated + atomic write).",
    dotPath: "Dot-path into config (e.g. `fleet.guildId`, `hosts.my-host.targetHost`).",
    dotValue: "Value to set as a string (use JSON value if you need objects/arrays/bools/numbers).",
    dotValueJson: "Value to set as JSON (e.g. `true`, `123`, `{...}`, `[...]`).",
  },
  bots: {
    botId: "Stable bot identifier (used in ports/services and config keys). Must match existing fleet conventions.",
  },
  providers: {
    guildId: "Discord guild/server ID used by the Discord provider.",
    discordTokenSecret: "Secret name for this bot’s Discord token (stored on disk; never in Convex). Default: `discord_token_<bot>`.",
  },
  models: {
    providerKey: "Model provider key prefix used in model ids (e.g. `openai`, `anthropic`, `minimax`).",
    secretName: "Secret name that stores the API key/token for this provider (values live in sops-encrypted host secrets).",
    apiKey: "API key/token value to write into host secrets (never stored in Convex). Leave blank to keep existing.",
    writeApiKeysHost: "Host whose encrypted secrets will receive the model provider API keys you enter here.",
    primaryModel: "Primary model id for this bot (format: `provider/model`). Overrides host default model.",
    botSelect: "Select which bot you’re editing advanced model provider config for.",
    modelsJson5: "Raw JSON5 for `clawdbot.models` (providers, routing, costs, etc). Do not embed secrets; use env via modelSecrets.",
  },
  secrets: {
    host: "Host whose encrypted secrets you’re initializing/verifying/syncing.",
    allowPlaceholders: "Allow `<PLACEHOLDER>` values during init (unsafe; use only for dry scaffolding).",
    adminPassword: "Optional admin password used to generate a yescrypt hash via Nix.",
    adminPasswordHash: "Precomputed yescrypt hash (`$y$…`). Stored as `admin_password_hash` secret.",
    tailscaleAuthKey: "Tailscale auth key for joining the tailnet (only required for Tailscale-based access).",
    discordToken: "Discord bot token value (written to encrypted secrets on disk).",
    extraSecret: "Additional secret value written to encrypted YAML under `secrets/hosts/<host>`.",
  },
  doctor: {
    host: "Host to run checks against (defaults to config default host).",
    scope: "Subset of checks to run (repo/bootstrap/server-deploy/cattle/all).",
  },
  bootstrap: {
    host: "Host entry to bootstrap/provision.",
    mode: "`nixos-anywhere` provisions a fresh server; `image` uses an existing image flow.",
    force: "Skip doctor gate checks. Risky; prefer fixing doctor findings first.",
    dryRun: "Show commands without executing (safe preview).",
  },
} as const
